// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<main.Config>;

export function OrganizeFile(arg1:string,arg2:boolean):Promise<Record<string, any>>;

export function SaveSettings(arg1:main.Config):Promise<string>;

export function ScanFolder(arg1:string):Promise<Array<main.FileInfo>>;

export function SelectFolder():Promise<string>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<string>;
