// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OrganizeFile(arg1, arg2) {
  return window['go']['main']['App']['OrganizeFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function TestConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3, arg4);
}
